// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {models} from '../models';

export function CancelJob(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function DeleteHistoryItem(arg1:string):Promise<void>;

export function GetDownloadPath(arg1:string):Promise<string>;

export function GetHistory():Promise<Array<main.HistoryItem>>;

export function GetJobStatus(arg1:string):Promise<models.JobStatus>;

export function OpenDownloadFolder():Promise<void>;

export function OpenFileLocation(arg1:string):Promise<void>;

export function SaveAsZip(arg1:string):Promise<string>;

export function StartScrape(arg1:string,arg2:string):Promise<main.ScrapeResponse>;
