// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelJob(arg1) {
  return window['go']['main']['App']['CancelJob'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function DeleteHistoryItem(arg1) {
  return window['go']['main']['App']['DeleteHistoryItem'](arg1);
}

export function GetDownloadPath(arg1) {
  return window['go']['main']['App']['GetDownloadPath'](arg1);
}

export function GetHistory() {
  return window['go']['main']['App']['GetHistory']();
}

export function GetJobStatus(arg1) {
  return window['go']['main']['App']['GetJobStatus'](arg1);
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function OpenFileLocation(arg1) {
  return window['go']['main']['App']['OpenFileLocation'](arg1);
}

export function SaveAsZip(arg1) {
  return window['go']['main']['App']['SaveAsZip'](arg1);
}

export function StartScrape(arg1, arg2) {
  return window['go']['main']['App']['StartScrape'](arg1, arg2);
}
