// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDownloadPath(arg1) {
  return window['go']['main']['App']['GetDownloadPath'](arg1);
}

export function GetJobStatus(arg1) {
  return window['go']['main']['App']['GetJobStatus'](arg1);
}

export function OpenDownloadFolder() {
  return window['go']['main']['App']['OpenDownloadFolder']();
}

export function SelectSaveLocation(arg1) {
  return window['go']['main']['App']['SelectSaveLocation'](arg1);
}

export function StartScrape(arg1, arg2) {
  return window['go']['main']['App']['StartScrape'](arg1, arg2);
}
