// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {main} from '../models';

export function GetDownloadPath(arg1:string):Promise<string>;

export function GetJobStatus(arg1:string):Promise<models.JobStatus>;

export function OpenDownloadFolder():Promise<void>;

export function SelectSaveLocation(arg1:string):Promise<string>;

export function StartScrape(arg1:string,arg2:string):Promise<main.ScrapeResponse>;
